### ISSUE TITLE
Hero Class

### ISSUE THREAD

**Issue by Havie** [adammyhre/Unity-Inventory-System#2]
Heya,

Came across your project from the Better Save/Load using Data Binding in Unity YT video.

I cloned the repo but I do not appear to have the Hero.cs class? Looks like it should be in the System namespace implying it would have its own Systems folder? (can be seen in your video)

Can you confirm the location of this file?

**Comment by adammyhre** [comment]
The repo is really meant to be a reference to the systems being built in the video so that you can see how you might apply such techniques to your own game, and not really for cloning.  As such, files like the Hero class I use in my own game, and it's supporting classes are not included in this repository.  They are just used in the video to illustrate the integration of the systems being created.  I hope, however, that you can take this example and adapt it to your own use case.
